trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python39:
        python.version: '3.9'
    maxParallel: 1

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: pip install robotframework robotframework-seleniumlibrary allure-robotframework
    displayName: 'Run robot installation'
  - powershell: robot --listener 'allure_robotframework;./results/allure' ./TestCases; exit 0
    displayName: 'Run Robot Scripts'
  - powershell: allure serve results/allure
    displayName: 'Execute Results'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: outputxunit.xml
      condition: succeededOrFailed()
      displayName: 'Publish Test Results outputxunit.xml'